project:
  type: book

book:
  title: "Python Foundation Course - ZeOmega"
  author: "Anand Chitipothu"
  date: "5/13/2024"
  chapters:
    - index.qmd
    - syllabus.qmd
    - references.qmd
    - part: Live Notes
      chapters:
        - live-notes/day1.ipynb
        - live-notes/day2.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



