project:
  type: book

book:
  title: "Python Foundation Course - ZeOmega"
  author: "Anand Chitipothu"
  date: "5/13/2024"
  chapters:
    - index.qmd
    - syllabus.qmd
    - taste-of-python.qmd
    - iteration-patterns.qmd
    - dictionaries.ipynb
    - re.qmd
    - writing-custom-modules.qmd
    - organizing-python-code.qmd
    - testing.qmd
    - part: Cookbook
      href: cookbook/index.qmd
      chapters:
        - cookbook/dates.qmd
        - cookbook/tabulate.qmd
    - part: Assignments
      href: assignments/index.qmd
      chapters:
        - assignments/assignment-01.qmd
        - assignments/assignment-02.qmd
        - assignments/assignment-03.qmd
        - assignments/assignment-04.qmd
    - part: Live Notes
      href: live-notes/index.qmd
      chapters:
        - live-notes/day1.ipynb
        - live-notes/day2.ipynb
        - live-notes/day3.ipynb
        - live-notes/day4.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



