project:
  type: book

book:
  title: "Python Foundation Course - ZeOmega"
  author: "Anand Chitipothu"
  date: "5/13/2024"
  chapters:
    - index.qmd
    - syllabus.qmd
    - taste-of-python.qmd
    - iteration-patterns.qmd
    - dictionaries.ipynb
    - re.qmd
    - writing-custom-modules.qmd
    - organizing-python-code.qmd
    - testing.qmd

    - part: Live Notes
      chapters:
        - live-notes/day1.ipynb
        - live-notes/day2.ipynb
        - live-notes/day3.ipynb
        - live-notes/day4.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



